# Generated by Django 4.2.6 on 2023-11-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phishing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="text_mail",
            name="message_embedding",
            field=models.TextField(null=True),
        ),
    ]
