# Generated by Django 4.2.6 on 2023-11-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phishing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account_numbers",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("account_number", models.CharField(max_length=50)),
                ("search_cnt", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Phone_numbers",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("phone_number", models.CharField(max_length=50)),
                ("search_cnt", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("embedding", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Text_KorCCVi",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("transcript", models.TextField()),
                ("label", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Text_mail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
                ("label", models.BooleanField(null=True)),
                ("phone_number", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Wave",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("spectrogram", models.BigIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name="organizations",
            old_name="number",
            new_name="call",
        ),
        migrations.RenameField(
            model_name="organizations",
            old_name="cat",
            new_name="category",
        ),
    ]
