# Generated by Django 4.2.6 on 2023-11-06 07:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("phishing", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organizations",
            old_name="number",
            new_name="call",
        ),
        migrations.RenameField(
            model_name="organizations",
            old_name="cat",
            new_name="category",
        ),
    ]
