# Generated by Django 4.2.6 on 2023-11-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phishing", "0002_rename_number_organizations_call_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account_numbers",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("account_number", models.CharField(max_length=50)),
                ("count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Phone_numbers",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("phone_number", models.CharField(max_length=50)),
                ("count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Text_KorCCVi",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("transcript", models.TextField()),
                ("label", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Text_mail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("transcript", models.TextField()),
                ("label", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Wave",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("spectrogram", models.BigIntegerField()),
            ],
        ),
    ]
