# Generated by Django 4.2.6 on 2023-11-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "phishing",
            "0002_account_numbers_phone_numbers_sentence_text_korccvi_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="text_mail",
            name="phone_number",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
