# Generated by Django 4.2.6 on 2023-11-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "phishing",
            "0003_account_numbers_phone_numbers_text_korccvi_text_mail_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="text_mail",
            name="filename",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
