# Generated by Django 4.2.6 on 2023-11-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phishing", "0005_alter_text_mail_filename"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("embedding", models.TextField()),
            ],
        ),
    ]
