# Generated by Django 4.2.6 on 2023-11-14 01:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("phishing", "0006_sentence"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account_numbers",
            old_name="count",
            new_name="search_cnt",
        ),
        migrations.RenameField(
            model_name="phone_numbers",
            old_name="count",
            new_name="search_cnt",
        ),
    ]
